// Generated by gencpp from file ari_pkg/msgPOIRequest.msg
// DO NOT EDIT!


#ifndef ARI_PKG_MESSAGE_MSGPOIREQUEST_H
#define ARI_PKG_MESSAGE_MSGPOIREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ari_pkg
{
template <class ContainerAllocator>
struct msgPOIRequest_
{
  typedef msgPOIRequest_<ContainerAllocator> Type;

  msgPOIRequest_()
    : poi_names()  {
    }
  msgPOIRequest_(const ContainerAllocator& _alloc)
    : poi_names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _poi_names_type;
  _poi_names_type poi_names;





  typedef boost::shared_ptr< ::ari_pkg::msgPOIRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ari_pkg::msgPOIRequest_<ContainerAllocator> const> ConstPtr;

}; // struct msgPOIRequest_

typedef ::ari_pkg::msgPOIRequest_<std::allocator<void> > msgPOIRequest;

typedef boost::shared_ptr< ::ari_pkg::msgPOIRequest > msgPOIRequestPtr;
typedef boost::shared_ptr< ::ari_pkg::msgPOIRequest const> msgPOIRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ari_pkg::msgPOIRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ari_pkg::msgPOIRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ari_pkg::msgPOIRequest_<ContainerAllocator1> & lhs, const ::ari_pkg::msgPOIRequest_<ContainerAllocator2> & rhs)
{
  return lhs.poi_names == rhs.poi_names;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ari_pkg::msgPOIRequest_<ContainerAllocator1> & lhs, const ::ari_pkg::msgPOIRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ari_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ari_pkg::msgPOIRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ari_pkg::msgPOIRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ari_pkg::msgPOIRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ari_pkg::msgPOIRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ari_pkg::msgPOIRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ari_pkg::msgPOIRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ari_pkg::msgPOIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26916b073f3bd9eee4b179ce0676ffa2";
  }

  static const char* value(const ::ari_pkg::msgPOIRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26916b073f3bd9eeULL;
  static const uint64_t static_value2 = 0xe4b179ce0676ffa2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ari_pkg::msgPOIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ari_pkg/msgPOIRequest";
  }

  static const char* value(const ::ari_pkg::msgPOIRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ari_pkg::msgPOIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] poi_names\n"
;
  }

  static const char* value(const ::ari_pkg::msgPOIRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ari_pkg::msgPOIRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poi_names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgPOIRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ari_pkg::msgPOIRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ari_pkg::msgPOIRequest_<ContainerAllocator>& v)
  {
    s << indent << "poi_names[]" << std::endl;
    for (size_t i = 0; i < v.poi_names.size(); ++i)
    {
      s << indent << "  poi_names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.poi_names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARI_PKG_MESSAGE_MSGPOIREQUEST_H
