// Generated by gencpp from file ari_pkg/msgPOI.msg
// DO NOT EDIT!


#ifndef ARI_PKG_MESSAGE_MSGPOI_H
#define ARI_PKG_MESSAGE_MSGPOI_H

#include <ros/service_traits.h>


#include <ari_pkg/msgPOIRequest.h>
#include <ari_pkg/msgPOIResponse.h>


namespace ari_pkg
{

struct msgPOI
{

typedef msgPOIRequest Request;
typedef msgPOIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct msgPOI
} // namespace ari_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ari_pkg::msgPOI > {
  static const char* value()
  {
    return "c796f839409775c93131126db79153f5";
  }

  static const char* value(const ::ari_pkg::msgPOI&) { return value(); }
};

template<>
struct DataType< ::ari_pkg::msgPOI > {
  static const char* value()
  {
    return "ari_pkg/msgPOI";
  }

  static const char* value(const ::ari_pkg::msgPOI&) { return value(); }
};


// service_traits::MD5Sum< ::ari_pkg::msgPOIRequest> should match
// service_traits::MD5Sum< ::ari_pkg::msgPOI >
template<>
struct MD5Sum< ::ari_pkg::msgPOIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ari_pkg::msgPOI >::value();
  }
  static const char* value(const ::ari_pkg::msgPOIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ari_pkg::msgPOIRequest> should match
// service_traits::DataType< ::ari_pkg::msgPOI >
template<>
struct DataType< ::ari_pkg::msgPOIRequest>
{
  static const char* value()
  {
    return DataType< ::ari_pkg::msgPOI >::value();
  }
  static const char* value(const ::ari_pkg::msgPOIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ari_pkg::msgPOIResponse> should match
// service_traits::MD5Sum< ::ari_pkg::msgPOI >
template<>
struct MD5Sum< ::ari_pkg::msgPOIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ari_pkg::msgPOI >::value();
  }
  static const char* value(const ::ari_pkg::msgPOIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ari_pkg::msgPOIResponse> should match
// service_traits::DataType< ::ari_pkg::msgPOI >
template<>
struct DataType< ::ari_pkg::msgPOIResponse>
{
  static const char* value()
  {
    return DataType< ::ari_pkg::msgPOI >::value();
  }
  static const char* value(const ::ari_pkg::msgPOIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARI_PKG_MESSAGE_MSGPOI_H
