// Generated by gencpp from file ari_pkg/msgPOIResponse.msg
// DO NOT EDIT!


#ifndef ARI_PKG_MESSAGE_MSGPOIRESPONSE_H
#define ARI_PKG_MESSAGE_MSGPOIRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ari_pkg
{
template <class ContainerAllocator>
struct msgPOIResponse_
{
  typedef msgPOIResponse_<ContainerAllocator> Type;

  msgPOIResponse_()
    : found(false)
    , poi_name_out()  {
    }
  msgPOIResponse_(const ContainerAllocator& _alloc)
    : found(false)
    , poi_name_out(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _found_type;
  _found_type found;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _poi_name_out_type;
  _poi_name_out_type poi_name_out;





  typedef boost::shared_ptr< ::ari_pkg::msgPOIResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ari_pkg::msgPOIResponse_<ContainerAllocator> const> ConstPtr;

}; // struct msgPOIResponse_

typedef ::ari_pkg::msgPOIResponse_<std::allocator<void> > msgPOIResponse;

typedef boost::shared_ptr< ::ari_pkg::msgPOIResponse > msgPOIResponsePtr;
typedef boost::shared_ptr< ::ari_pkg::msgPOIResponse const> msgPOIResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ari_pkg::msgPOIResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ari_pkg::msgPOIResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ari_pkg::msgPOIResponse_<ContainerAllocator1> & lhs, const ::ari_pkg::msgPOIResponse_<ContainerAllocator2> & rhs)
{
  return lhs.found == rhs.found &&
    lhs.poi_name_out == rhs.poi_name_out;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ari_pkg::msgPOIResponse_<ContainerAllocator1> & lhs, const ::ari_pkg::msgPOIResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ari_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ari_pkg::msgPOIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ari_pkg::msgPOIResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ari_pkg::msgPOIResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ari_pkg::msgPOIResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ari_pkg::msgPOIResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ari_pkg::msgPOIResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ari_pkg::msgPOIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d958e07ec49ea85622945a237e0c05b";
  }

  static const char* value(const ::ari_pkg::msgPOIResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d958e07ec49ea85ULL;
  static const uint64_t static_value2 = 0x622945a237e0c05bULL;
};

template<class ContainerAllocator>
struct DataType< ::ari_pkg::msgPOIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ari_pkg/msgPOIResponse";
  }

  static const char* value(const ::ari_pkg::msgPOIResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ari_pkg::msgPOIResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool found\n"
"string poi_name_out\n"
;
  }

  static const char* value(const ::ari_pkg::msgPOIResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ari_pkg::msgPOIResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.found);
      stream.next(m.poi_name_out);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgPOIResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ari_pkg::msgPOIResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ari_pkg::msgPOIResponse_<ContainerAllocator>& v)
  {
    s << indent << "found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.found);
    s << indent << "poi_name_out: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.poi_name_out);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARI_PKG_MESSAGE_MSGPOIRESPONSE_H
