// Generated by gencpp from file ari_pkg/msgs.msg
// DO NOT EDIT!


#ifndef ARI_PKG_MESSAGE_MSGS_H
#define ARI_PKG_MESSAGE_MSGS_H

#include <ros/service_traits.h>


#include <ari_pkg/msgsRequest.h>
#include <ari_pkg/msgsResponse.h>


namespace ari_pkg
{

struct msgs
{

typedef msgsRequest Request;
typedef msgsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct msgs
} // namespace ari_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ari_pkg::msgs > {
  static const char* value()
  {
    return "2b2d0cfdeb1bcfaa2e895bdcca41ec33";
  }

  static const char* value(const ::ari_pkg::msgs&) { return value(); }
};

template<>
struct DataType< ::ari_pkg::msgs > {
  static const char* value()
  {
    return "ari_pkg/msgs";
  }

  static const char* value(const ::ari_pkg::msgs&) { return value(); }
};


// service_traits::MD5Sum< ::ari_pkg::msgsRequest> should match
// service_traits::MD5Sum< ::ari_pkg::msgs >
template<>
struct MD5Sum< ::ari_pkg::msgsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ari_pkg::msgs >::value();
  }
  static const char* value(const ::ari_pkg::msgsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ari_pkg::msgsRequest> should match
// service_traits::DataType< ::ari_pkg::msgs >
template<>
struct DataType< ::ari_pkg::msgsRequest>
{
  static const char* value()
  {
    return DataType< ::ari_pkg::msgs >::value();
  }
  static const char* value(const ::ari_pkg::msgsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ari_pkg::msgsResponse> should match
// service_traits::MD5Sum< ::ari_pkg::msgs >
template<>
struct MD5Sum< ::ari_pkg::msgsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ari_pkg::msgs >::value();
  }
  static const char* value(const ::ari_pkg::msgsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ari_pkg::msgsResponse> should match
// service_traits::DataType< ::ari_pkg::msgs >
template<>
struct DataType< ::ari_pkg::msgsResponse>
{
  static const char* value()
  {
    return DataType< ::ari_pkg::msgs >::value();
  }
  static const char* value(const ::ari_pkg::msgsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARI_PKG_MESSAGE_MSGS_H
