// Generated by gencpp from file ari_pkg/wavs_msg.msg
// DO NOT EDIT!


#ifndef ARI_PKG_MESSAGE_WAVS_MSG_H
#define ARI_PKG_MESSAGE_WAVS_MSG_H

#include <ros/service_traits.h>


#include <ari_pkg/wavs_msgRequest.h>
#include <ari_pkg/wavs_msgResponse.h>


namespace ari_pkg
{

struct wavs_msg
{

typedef wavs_msgRequest Request;
typedef wavs_msgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct wavs_msg
} // namespace ari_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ari_pkg::wavs_msg > {
  static const char* value()
  {
    return "e6a881b942915d9139f8909f61208275";
  }

  static const char* value(const ::ari_pkg::wavs_msg&) { return value(); }
};

template<>
struct DataType< ::ari_pkg::wavs_msg > {
  static const char* value()
  {
    return "ari_pkg/wavs_msg";
  }

  static const char* value(const ::ari_pkg::wavs_msg&) { return value(); }
};


// service_traits::MD5Sum< ::ari_pkg::wavs_msgRequest> should match
// service_traits::MD5Sum< ::ari_pkg::wavs_msg >
template<>
struct MD5Sum< ::ari_pkg::wavs_msgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ari_pkg::wavs_msg >::value();
  }
  static const char* value(const ::ari_pkg::wavs_msgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ari_pkg::wavs_msgRequest> should match
// service_traits::DataType< ::ari_pkg::wavs_msg >
template<>
struct DataType< ::ari_pkg::wavs_msgRequest>
{
  static const char* value()
  {
    return DataType< ::ari_pkg::wavs_msg >::value();
  }
  static const char* value(const ::ari_pkg::wavs_msgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ari_pkg::wavs_msgResponse> should match
// service_traits::MD5Sum< ::ari_pkg::wavs_msg >
template<>
struct MD5Sum< ::ari_pkg::wavs_msgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ari_pkg::wavs_msg >::value();
  }
  static const char* value(const ::ari_pkg::wavs_msgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ari_pkg::wavs_msgResponse> should match
// service_traits::DataType< ::ari_pkg::wavs_msg >
template<>
struct DataType< ::ari_pkg::wavs_msgResponse>
{
  static const char* value()
  {
    return DataType< ::ari_pkg::wavs_msg >::value();
  }
  static const char* value(const ::ari_pkg::wavs_msgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARI_PKG_MESSAGE_WAVS_MSG_H
