// Generated by gencpp from file ari_pkg/wavs_msgResponse.msg
// DO NOT EDIT!


#ifndef ARI_PKG_MESSAGE_WAVS_MSGRESPONSE_H
#define ARI_PKG_MESSAGE_WAVS_MSGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ari_pkg
{
template <class ContainerAllocator>
struct wavs_msgResponse_
{
  typedef wavs_msgResponse_<ContainerAllocator> Type;

  wavs_msgResponse_()
    : msgResp()  {
    }
  wavs_msgResponse_(const ContainerAllocator& _alloc)
    : msgResp(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msgResp_type;
  _msgResp_type msgResp;





  typedef boost::shared_ptr< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> const> ConstPtr;

}; // struct wavs_msgResponse_

typedef ::ari_pkg::wavs_msgResponse_<std::allocator<void> > wavs_msgResponse;

typedef boost::shared_ptr< ::ari_pkg::wavs_msgResponse > wavs_msgResponsePtr;
typedef boost::shared_ptr< ::ari_pkg::wavs_msgResponse const> wavs_msgResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ari_pkg::wavs_msgResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ari_pkg::wavs_msgResponse_<ContainerAllocator1> & lhs, const ::ari_pkg::wavs_msgResponse_<ContainerAllocator2> & rhs)
{
  return lhs.msgResp == rhs.msgResp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ari_pkg::wavs_msgResponse_<ContainerAllocator1> & lhs, const ::ari_pkg::wavs_msgResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ari_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bc7275900b5ab950c42dea71449a4d0";
  }

  static const char* value(const ::ari_pkg::wavs_msgResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bc7275900b5ab95ULL;
  static const uint64_t static_value2 = 0x0c42dea71449a4d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ari_pkg/wavs_msgResponse";
  }

  static const char* value(const ::ari_pkg::wavs_msgResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msgResp\n"
;
  }

  static const char* value(const ::ari_pkg::wavs_msgResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msgResp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wavs_msgResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ari_pkg::wavs_msgResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ari_pkg::wavs_msgResponse_<ContainerAllocator>& v)
  {
    s << indent << "msgResp: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msgResp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARI_PKG_MESSAGE_WAVS_MSGRESPONSE_H
